<?php
/**
 * PickupTime
 *
 * PHP version 8.1
 *
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipstage API
 *
 * Wenn Sie die API verwenden möchten, wenden Sie sich bitte an den Support, um ein Authentifizierungstoken zu erhalten.
 *
 * The version of the OpenAPI document: 2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\shipstage\Model;

/**
 * PickupTime Class Doc Comment
 *
 * @description 09:00 - 13:00 (09:00-13:00), 13:00 - 17:00 (13:00-17:00), 08:00 - 16:00 (08:00-16:00)
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum PickupTime: string
{
    case _09_00_13_00 = '09:00-13:00';

    case _13_00_17_00 = '13:00-17:00';

    case _08_00_16_00 = '08:00-16:00';
}


