<?php
/**
 * ShipmentType
 *
 * PHP version 8.1
 *
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipstage API
 *
 * Wenn Sie die API verwenden möchten, wenden Sie sich bitte an den Support, um ein Authentifizierungstoken zu erhalten.
 *
 * The version of the OpenAPI document: 2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\shipstage\Model;

/**
 * ShipmentType Class Doc Comment
 *
 * @description Sale, Gift, Sample, Return, Repair, Documents, Commercial goods, Document, Commercial sample, Return of goods, Present
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ShipmentType: string
{
    case SALE = 'SALE';

    case GIFT = 'GIFT';

    case SAMPLE = 'SAMPLE';

    case _RETURN = 'RETURN';

    case REPAIR = 'REPAIR';

    case DOCUMENTS = 'DOCUMENTS';

    case COMMERCIAL_GOODS = 'COMMERCIAL_GOODS';

    case DOCUMENT = 'DOCUMENT';

    case COMMERCIAL_SAMPLE = 'COMMERCIAL_SAMPLE';

    case RETURN_OF_GOODS = 'RETURN_OF_GOODS';

    case PRESENT = 'PRESENT';
}


