<?php
/**
 * State
 *
 * PHP version 8.1
 *
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipstage API
 *
 * Wenn Sie die API verwenden möchten, wenden Sie sich bitte an den Support, um ein Authentifizierungstoken zu erhalten.
 *
 * The version of the OpenAPI document: 2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\shipstage\Model;

/**
 * State Class Doc Comment
 *
 * @description Alabama (AL), Alaska (AK), Arizona (AZ), Arkansas (AR), Colorado (CO), Connecticut (CT), Delaware (DE), Florida (FL), Georgia (GA), Hawaii (HI), Idaho (ID), Illinois (IL), Indiana (IN), Iowa (IA), Kalifornien (CA), Kansas (KS), Kentucky (KY), Louisiana (LA), Maine (ME), Maryland (MD), Massachusetts (MA), Michigan (MI), Minnesota (MN), Mississippi (MS), Missouri (MO), Montana (MT), Nebraska (NE), Nevada (NV), New Hampshire (NH), New Jersey (NJ), New Mexico (NM), New York (NY), North Carolina (NC), North Dakota (ND), Ohio (OH), Oklahoma (OK), Oregon (OR), Pennsylvania (PA), Rhode Island (RI), South Carolina (SC), South Dakota (SD), Tennessee (TN), Texas (TX), Utah (UT), Vermont (VT), Virginia (VA), Washington (WA), West Virginia (WV), Wisconsin (WI), Wyoming (WY)
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum State: string
{
    case AL = 'AL';

    case AK = 'AK';

    case AZ = 'AZ';

    case AR = 'AR';

    case CO = 'CO';

    case CT = 'CT';

    case DE = 'DE';

    case FL = 'FL';

    case GA = 'GA';

    case HI = 'HI';

    case ID = 'ID';

    case IL = 'IL';

    case IN = 'IN';

    case IA = 'IA';

    case CA = 'CA';

    case KS = 'KS';

    case KY = 'KY';

    case LA = 'LA';

    case ME = 'ME';

    case MD = 'MD';

    case MA = 'MA';

    case MI = 'MI';

    case MN = 'MN';

    case MS = 'MS';

    case MO = 'MO';

    case MT = 'MT';

    case NE = 'NE';

    case NV = 'NV';

    case NH = 'NH';

    case NJ = 'NJ';

    case NM = 'NM';

    case NY = 'NY';

    case NC = 'NC';

    case ND = 'ND';

    case OH = 'OH';

    case OK = 'OK';

    case _OR = 'OR';

    case PA = 'PA';

    case RI = 'RI';

    case SC = 'SC';

    case SD = 'SD';

    case TN = 'TN';

    case TX = 'TX';

    case UT = 'UT';

    case VT = 'VT';

    case VA = 'VA';

    case WA = 'WA';

    case WV = 'WV';

    case WI = 'WI';

    case WY = 'WY';
}


