<?php
/**
 * TermsOfShipment
 *
 * PHP version 8.1
 *
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipstage API
 *
 * Wenn Sie die API verwenden möchten, wenden Sie sich bitte an den Support, um ein Authentifizierungstoken zu erhalten.
 *
 * The version of the OpenAPI document: 2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\shipstage\Model;

/**
 * TermsOfShipment Class Doc Comment
 *
 * @description Delivered At Place (DAP), Delivered Duty Paid (DDP), Delivered at Place Unloaded (DDU)
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum TermsOfShipment: string
{
    case DAP = 'DAP';

    case DDP = 'DDP';

    case DDU = 'DDU';
}


