<?php
/**
 * DangerousGoodTypeTest
 *
 * PHP version 8.1
 *
 * @package  kruegge82\shipstage
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipstage API
 *
 * Wenn Sie die API verwenden möchten, wenden Sie sich bitte an den Support, um ein Authentifizierungstoken zu erhalten.
 *
 * The version of the OpenAPI document: 2.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kruegge82\shipstage\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DangerousGoodTypeTest Class Doc Comment
 *
 * @description No (no), Lithium Metal Batterie loose (UN3090) (li_metal_loose), Lithium Metal Batteries contained in equipment (UN3091) (li_metal_cont_eq), Lithium Metal Batteries packed with equipment (UN3091) (li_metal_pack_eq), Lithium-Ion Batteries (UN3480) (li_ion), Lithium-Ion Batteries contained in equipment (UN3481) (li_ion_cont_eq), Lithium-Ion Batteries packed in equipment (UN3481) (li_ion_pack_eq), Biological substance, category B (UN3373) (bio_sub_b), Genetically modified organisms (UN3245) (gmo), Dry ice (UN1845) (dry_ice), Dangerous goods in limited quantity (dg_limited_qty), Dangerous goods in excepted quantity (dg_excepted_qty), Fully regulated dangerous goods (full_reg_dg)
 * @package     kruegge82\shipstage
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DangerousGoodTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DangerousGoodType"
     */
    public function testDangerousGoodType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
